return {
-- TODO: This broke. Should I replace it with something?
--   {
--     "nvim-neorg/neorg",
--     event = "VeryLazy",
--
--     build = ":Neorg sync-parsers",
--     dependencies = { "nvim-lua/plenary.nvim" },
--     config = function()
--       require("neorg").setup({
--         load = {
--           ["core.defaults"] = {},
--           ["core.concealer"] = {},
--           ["core.keybinds"] = {
--             config = {
--               default_keybinds = true,
--               neorg_leader = "<leader>n",
--             },
--           },
--           ["core.dirman"] = {
--             config = {
--               workspaces = {
--                 work = "~/notes/work",
--                 home = "~/notes/home",
--               },
--             },
--           },
--         },
--       })
--     end,
--   },
}
